Vagrant.configure(2) do |config|

  # CentOS 5
  config.vm.define "centos5" do |centos5|
    centos5.vm.box = "hfm4/centos5"
    centos5.vm.hostname = "epel-centos5"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "epel-el5"
      vbox.cpus = 1
      vbox.memory = 128
    end
  end

  # CentOS 6
  config.vm.define "epel-el6" do |centos6|
    centos6.vm.box = "centos/centos6"
    centos6.vm.hostname = "epel-centos6"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "epel-el6"
      vbox.cpus = 1
      vbox.memory = 128
    end
  end

  # CentOS 7
  config.vm.define "epel-el7" do |centos7|
    centos7.vm.box = "centos/centos7"
    centos7.vm.hostname = "epel-centos7"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "epel-el7"
      vbox.cpus = 1
      vbox.memory = 128
    end
  end

  # RHEL 7
  config.vm.define "epel-rhel7" do |centos7|
    centos7.vm.box = "samdoran/rhel7"
    centos7.vm.hostname = "epel-rhel7"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "epel-rhel7"
      vbox.cpus = 1
      vbox.memory = 256
    end
  end

  config.vm.provision "shell", inline: "sudo yum -y install python-simplejson"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant.yml"
  end

end
